PUT http://localhost:3000/api/menu/294
Content-Type: application/json

{
    "nombre": "Morcipan",
    "descripcion": "Delicioso morcilla en formato sanguche",
    "precio": 450.00,
    "id_categoria": 7,
    "id_subcategoria": null,
    "vegano": false,
    "celiaco": false,
    "vegetariano": false
}
